# docker/docker-compose.yml
version: '3.8'

services:
  client:
    build:
      context: ..
      dockerfile: docker/Dockerfile.client
    ports:
      - "3000:3000"

  server:
    build:
      context: ..
      dockerfile: docker/Dockerfile.server
    ports:
      - "5000:5000"
    env_file:
      - ../server/.env
